[package]
name = "bom_forge"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
clap = "4.5.38"
csv = "1.3.1"
nom = "8.0.0"
reqwest = "0.12.15"
thiserror = "2.0.12"
tokio = "1.45.0"
